import { getGames, getGame } from './api.js';
const DATA_URL = 'data/games.json';
export async function loadGames() { try { const games = await getGames(); return Array.isArray(games) ? games.filter(isValidGame) : []; } catch (error) { if (error.status) throw error; const response = await fetch(DATA_URL); if (!response.ok) throw new Error('Game data could not be loaded.'); const data = await response.json(); return Array.isArray(data) ? data.filter(isValidGame) : []; } }
export async function loadGame(slug) { try { return await getGame(slug); } catch (error) { if (error.status !== 404 && error.status) throw error; const games = await loadGames(); const game = games.find(item => item.slug === slug); if (!game) throw error; return game; } }
export function isValidGame(game) { return game && typeof game.id === 'string' && typeof game.title === 'string' && typeof game.slug === 'string' && typeof game.category === 'string' && typeof game.coverImage === 'string'; }
export function gameCard(game) { const card=document.createElement('article'); card.className='game-card'; const link=document.createElement('a'); link.href=`game.html?slug=${encodeURIComponent(game.slug)}`; link.setAttribute('aria-label',`View details for ${game.title}`); const image=document.createElement('img'); image.className='game-cover'; image.src=game.coverImage; image.alt=`${game.title} cover artwork`; image.loading='lazy'; image.addEventListener('error',()=>{image.src='assets/images/fallback.svg';image.alt='Cover artwork unavailable';}); link.append(image); const body=document.createElement('div'); body.className='game-card__body'; const meta=document.createElement('div'); meta.className='game-card__meta'; meta.append(text(game.category),text(game.platform?.[0]||'')); body.append(meta); const heading=document.createElement('h3'); heading.textContent=game.title; body.append(heading); const description=document.createElement('p'); description.textContent=game.shortDescription||'Explore this game in the catalog.'; body.append(description); const details=document.createElement('a'); details.className='card-link'; details.href=link.href; details.textContent='View details '; const arrow=document.createElement('span'); arrow.textContent='→'; details.append(arrow); body.append(details); card.append(link,body); return card; }
function text(value){const span=document.createElement('span');span.textContent=value;return span;}
export function renderShell(){const header=document.querySelector('[data-site-header]');if(header){header.className='site-header';header.innerHTML='<a class="brand" href="index.html"><span class="brand-mark" aria-hidden="true"></span>arcade atlas</a><nav class="nav-links" aria-label="Main navigation"><a href="games.html">Games</a><a href="about.html">About</a><a class="nav-cta" href="games.html">Explore ↗</a></nav>';}const footer=document.querySelector('[data-site-footer]');if(footer){footer.className='site-footer';footer.innerHTML='<a class="brand" href="index.html">arcade atlas</a><p>Curated discovery for authorized game downloads · <span>© 2026</span></p>';}}
function showError(container,message='We couldn’t load the catalog right now. Please try again later.'){container.replaceChildren();const state=document.createElement('div');state.className='error-state';state.textContent=message;container.append(state);}
renderShell(); const featured=document.querySelector('[data-featured-games]');const latest=document.querySelector('[data-latest-games]');const categories=document.querySelector('[data-categories]');if(featured||latest)loadGames().then(games=>{if(featured)featured.replaceChildren(...games.filter(g=>g.featured).map(gameCard));if(latest)latest.replaceChildren(...games.slice().sort((a,b)=>(b.releaseDate||'').localeCompare(a.releaseDate||'')).slice(0,3).map(gameCard));if(categories){const counts=games.reduce((map,g)=>map.set(g.category,(map.get(g.category)||0)+1),new Map());counts.forEach((count,category)=>{const a=document.createElement('a');a.className='category';a.href=`games.html?category=${encodeURIComponent(category)}`;a.textContent=category;const small=document.createElement('small');small.textContent=`${count} ${count===1?'title':'titles'}`;a.append(small);categories.append(a);});}}).catch(error=>{if(featured)showError(featured,error.status===429?'The catalog is busy. Please try again shortly.':undefined);if(latest)showError(latest);});
