import express from 'express';
import crypto from 'node:crypto';
import { createDatabase } from './db.js';
import { createPasswordHash, verifyPassword, randomSessionToken, hashToken, now, id } from './security.js';
import { validateGame } from './validation.js';
import { requireAuth } from './auth-middleware.js';

const publicGame = row => ({ ...row, tags: JSON.parse(row.tags_json), platform: JSON.parse(row.platforms_json), category: row.category_name, coverImage: row.cover_image, shortDescription: row.short_description, releaseDate: row.release_date, downloadUrl: row.download_url || '' , demo: false });
function gameRow(db, idOrSlug, publishedOnly = false) { return db.prepare(`SELECT g.*, c.name category_name, d.url download_url FROM games g JOIN categories c ON c.id=g.category_id LEFT JOIN downloads d ON d.game_id=g.id AND d.active=1 WHERE ${idOrSlug === 'slug' ? 'g.slug=?' : 'g.id=?'} AND g.deleted_at IS NULL ${publishedOnly ? "AND g.status='published'" : ''}`).get(idOrSlug === 'slug' ? arguments[2] : arguments[1]); }
function mapRow(row) { return publicGame(row); }
function ensureCategory(db, name) { const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); let category = db.prepare('SELECT * FROM categories WHERE name = ?').get(name); if (!category) { category = { id: id(), slug, name, created_at: now() }; db.prepare('INSERT INTO categories (id,slug,name,created_at) VALUES (@id,@slug,@name,@created_at)').run(category); } return category; }
function saveGame(db, input, existing = null) { const category = ensureCategory(db, input.category); const timestamp = now(); const game = { ...input, id: existing?.id || id(), categoryId: category.id, tagsJson: JSON.stringify(input.tags), platformsJson: JSON.stringify(input.platform), status: existing?.status || 'draft', createdAt: existing?.created_at || timestamp, updatedAt: timestamp }; if (existing) db.prepare(`UPDATE games SET title=@title,slug=@slug,short_description=@shortDescription,description=@description,category_id=@categoryId,tags_json=@tagsJson,version=@version,platforms_json=@platformsJson,file_size=@fileSize,release_date=@releaseDate,cover_image=@coverImage,featured=@featured,updated_at=@updatedAt WHERE id=@id`).run({ ...game, featured: input.featured ? 1 : 0 }); else db.prepare(`INSERT INTO games (id,title,slug,short_description,description,category_id,tags_json,version,platforms_json,file_size,release_date,cover_image,featured,status,created_at,updated_at) VALUES (@id,@title,@slug,@shortDescription,@description,@categoryId,@tagsJson,@version,@platformsJson,@fileSize,@releaseDate,@coverImage,@featured,@status,@createdAt,@updatedAt)`).run({ ...game, featured: input.featured ? 1 : 0 }); if (input.downloadUrl) db.prepare('INSERT INTO downloads (id,game_id,url,active,created_at,updated_at) VALUES (?,?,?,?,?,?)').run(id(), game.id, input.downloadUrl, 1, timestamp, timestamp); return game.id; }

export function createApp({ db = createDatabase(), sessionDays = 7 } = {}) {
  const app = express(); app.use(express.json({ limit: '100kb' })); app.use((req, res, next) => { res.setHeader('Access-Control-Allow-Origin', process.env.PUBLIC_SITE_URL || 'http://localhost:8000'); res.setHeader('Access-Control-Allow-Credentials', 'true'); res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization'); res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PATCH,DELETE,OPTIONS'); if (req.method === 'OPTIONS') return res.sendStatus(204); next(); });
  app.get('/api/health', (req,res) => res.json({ ok: true }));
  app.post('/api/auth/login', (req,res) => { const email = String(req.body?.email || '').trim().toLowerCase(); const password = String(req.body?.password || ''); const admin = db.prepare('SELECT * FROM admins WHERE email=? AND disabled_at IS NULL').get(email); if (!admin || !verifyPassword(password, admin.password_hash)) return res.status(401).json({ error: 'Invalid email or password.' }); const token = randomSessionToken(); db.prepare('INSERT INTO sessions (token_hash,admin_id,expires_at,created_at) VALUES (?,?,?,?)').run(hashToken(token), admin.id, new Date(Date.now()+sessionDays*86400000).toISOString(), now()); db.prepare('UPDATE admins SET last_login_at=? WHERE id=?').run(now(), admin.id); res.cookie('arcade_session', token, { httpOnly:true, sameSite:'lax', secure:process.env.NODE_ENV==='production', maxAge:sessionDays*86400000 }); res.json({ admin: { id:admin.id, email:admin.email, role:admin.role } }); });
  app.post('/api/auth/logout', (req,res) => { const raw = req.headers.cookie?.match(/(?:^|; )arcade_session=([^;]+)/)?.[1]; if (raw) db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hashToken(decodeURIComponent(raw))); res.clearCookie('arcade_session'); res.sendStatus(204); });
  app.get('/api/games', (req,res) => { const q=String(req.query.q||'').trim().toLowerCase(); const category=String(req.query.category||''); const rows=db.prepare(`SELECT g.*,c.name category_name,d.url download_url FROM games g JOIN categories c ON c.id=g.category_id LEFT JOIN downloads d ON d.game_id=g.id AND d.active=1 WHERE g.status='published' AND g.deleted_at IS NULL ORDER BY g.release_date DESC, g.created_at DESC`).all().map(mapRow).filter(game => (!q || [game.title,game.category,...game.tags].join(' ').toLowerCase().includes(q)) && (!category || game.category===category)); res.json(rows); });
  app.get('/api/games/:slug', (req,res) => { const row=db.prepare(`SELECT g.*,c.name category_name,d.url download_url FROM games g JOIN categories c ON c.id=g.category_id LEFT JOIN downloads d ON d.game_id=g.id AND d.active=1 WHERE g.slug=? AND g.status='published' AND g.deleted_at IS NULL`).get(req.params.slug); if(!row) return res.status(404).json({error:'Game not found.'}); res.json(mapRow(row)); });
  app.use('/api/admin', requireAuth(db));
  app.get('/api/admin/me', (req,res)=>res.json({admin:req.admin}));
  app.get('/api/admin/stats', (req,res)=>res.json({total:db.prepare("SELECT count(*) count FROM games WHERE deleted_at IS NULL").get().count,published:db.prepare("SELECT count(*) count FROM games WHERE status='published' AND deleted_at IS NULL").get().count,drafts:db.prepare("SELECT count(*) count FROM games WHERE status!='published' AND deleted_at IS NULL").get().count}));
  app.get('/api/admin/games', (req,res)=>{ const rows=db.prepare(`SELECT g.*,c.name category_name,d.url download_url FROM games g JOIN categories c ON c.id=g.category_id LEFT JOIN downloads d ON d.game_id=g.id AND d.active=1 WHERE g.deleted_at IS NULL ORDER BY g.updated_at DESC`).all(); res.json(rows.map(mapRow)); });
  app.post('/api/admin/games', (req,res)=>{ const checked=validateGame(req.body); if(!checked.valid) return res.status(422).json({error:'Validation failed.',fields:checked.errors}); const gameId=saveGame(db,checked.game); res.status(201).json({id:gameId}); });
  app.patch('/api/admin/games/:id', (req,res)=>{ const existing=db.prepare('SELECT * FROM games WHERE id=? AND deleted_at IS NULL').get(req.params.id); if(!existing) return res.status(404).json({error:'Game not found.'}); const duplicate=db.prepare('SELECT slug FROM games WHERE slug=? AND id!=?').get(req.body.slug,req.params.id); const checked=validateGame(req.body,{existingSlug:duplicate?.slug}); if(!checked.valid) return res.status(422).json({error:'Validation failed.',fields:checked.errors}); saveGame(db,checked.game,existing); res.json({ok:true}); });
  app.post('/api/admin/games/:id/publish', (req,res)=>transition(db,req,res,'published'));
  app.post('/api/admin/games/:id/unpublish', (req,res)=>transition(db,req,res,'draft'));
  app.delete('/api/admin/games/:id', (req,res)=>{ const result=db.prepare('UPDATE games SET deleted_at=?,status=\'archived\',updated_at=? WHERE id=? AND deleted_at IS NULL').run(now(),now(),req.params.id); if(!result.changes) return res.status(404).json({error:'Game not found.'}); res.sendStatus(204); });
  if (process.env.SERVE_STATIC !== 'false') app.use(express.static(new URL('../', import.meta.url).pathname));
  return app;
}
function transition(db,req,res,status) { const game=db.prepare('SELECT * FROM games WHERE id=? AND deleted_at IS NULL').get(req.params.id); if(!game) return res.status(404).json({error:'Game not found.'}); if(status==='published' && !db.prepare('SELECT 1 FROM downloads WHERE game_id=? AND active=1').get(game.id)) return res.status(422).json({error:'A valid authorized download URL is required before publishing.'}); db.prepare('UPDATE games SET status=?,published_at=?,updated_at=? WHERE id=?').run(status,status==='published'?now():null,now(),game.id); res.json({ok:true,status}); }
